version: '3.6'

services:
  mongo:
    container_name: chatuimongo
    image: mongo:latest
    restart: always
    ports:
      - ${MONGODB_PORT:-27018}:${MONGODB_PORT:-27018}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: chatui
    env_file:
      - .env.local
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  chatui:
    container_name: chatui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo-express:
    container_name: chatuimongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8082}:${MONGO_EXPRESS_PORT:-8082}
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT:-27018}
      ME_CONFIG_MONGODB_AUTH_DATABASE: chatui
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongo:${MONGODB_PORT:-27018}/
    depends_on:
      - mongo

volumes:
  mongodb-data:
    name: chatui-mongodb-data
  mongodb-configdb:
    name: chatui-mongodb-configdb
