version: '3.6'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGO_INITDB_DATABASE: chatui
    env_file:
      - .env.local
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  chatui:
    container_name: chatui
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatui
      - ME_CONFIG_MONGODB_ADMINUSERNAME= ${MONGODB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD= ${MONGODB_PASSWORD:-password}
      - ME_CONFIG_MONGODB_URL= mongodb://${MONGODB_USERNAME:-root}:${MONGODB_PASSWORD:-password}@mongo:${MONGODB_PORT:-27017}/
    depends_on:
      - mongo

volumes:
  mongodb-data:
    name: chatui-mongodb-data
  mongodb-configdb:
    name: chatui-mongodb-configdb

# services:
#   mongo:
#     container_name: mongo
#     image: mongo:latest
#     restart: always
#     ports:
#       - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
#     volumes:
#       - ${MONGODB_PATH:-./mongodb}:/data/db
#     # TODO: add auth

#   chatgpt_telegram_bot:
#     container_name: chatgpt_telegram_bot
#     command: python3 bot/bot.py
#     restart: always
#     build:
#       context: "."
#       dockerfile: Dockerfile
#     depends_on:
#       - mongo

#   mongo_express:
#     container_name: mongo-express
#     image: mongo-express:latest
#     restart: always
#     ports:
#       - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
#     environment:
#       - ME_CONFIG_MONGODB_SERVER=mongo
#       - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
#       - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#       - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
#       - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
#       - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
#     depends_on:
#       - mongo
