version: '3.6'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: chatui
    env_file:
      - .env.local
    volumes:
      - mongo-configdb:/data/configdb
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  chatui:
    container_name: chatui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongo:${MONGODB_PORT:-27017}/
    depends_on:
      - mongo

volumes:
  mongo-data:
    name: mongo-data
  mongo-configdb:
    name: mongo-configdb
